database:
  # Should plugin use SQLite database as data storage?
  # Specify 'true' for SQLite or 'false' for MySQL
  use-sqlite: true

  # MySQL configuration
  host: localhost
  port: 3306
  name: revoeco
  user: admin
  password: revoeco

  # SQLite configuration
  file: database.db

dateformat-pattern: "dd.MM.yy - kk:mm:ss"